name: Pipeline deploy to a production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publiher-docker-image:
    name: Publiher docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push to docker hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: idrams56/quarkus-tasks
  redeploy:
    name: Redeploy to a remore web-server
    runs-on: ubuntu-latest
    needs: [publiher-docker-image]
    steps:
      - name: Deploy docker container
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}


